name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . -t your-image-name
    - name: Push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push your-image-name
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f your-kubernetes-config.yaml
